### PR TITLE
RL and DP refactor

### PR DESCRIPTION
**Pull request by fabiorobayo**
This pull request addresses #13

### CODE REVIEW

**Comment by hbk-ronak** [comment]
These commits look fine to me!

@fabiorobayo you can add yourself as the author in setup.py file!

**Review by hbk-ronak — COMMENTED** [review]
can you also add ```.idea/``` in gitignore?

**Review by hbk-ronak — COMMENTED** [review]
can you make sure you follow numpydoc formatting everywhere?

**Review by hbk-ronak — COMMENTED** [review]
For tests cases you are reading file by writing absolute path can you make it relative path? It is confusing for others!

**Comment by fabiorobayo** [comment]
@hbk-ronak initially it was a relative path but the automated build wouldn't find the file, I tried to use pathlib to fix it but it still didn't work, the setup of the environment used to do the automated build is not visible to me so I can't really make sure it will find the file. We added a try/except to handle absolute and relative cases.

**Comment by hbk-ronak** [comment]
@fabiorobayo you can use ./tests/filename as the path it should work

**Comment by fabiorobayo** [comment]
@hbk-ronak didn't work locally for me. Can we merge this pull request and create an issue for the filepath?

**Comment by hbk-ronak** [comment]
@fabiorobayo I've already approved. We are waiting for a review from professor. @PawPol can you review the code?

**Pull request merged**
